# Generated by Django 4.2.24 on 2025-10-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_paymentdetail_insurance_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedOfflinePayments',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('details', models.JSONField(db_column='Details')),
                ('error_message', models.TextField(db_column='ErrorMessage')),
            ],
            options={
                'db_table': 'UnmatchedOfflinePayments',
                'managed': True,
            },
        ),
    ]
