# Generated by Django 4.2.25 on 2025-11-27 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_create_tblclaimadmin'),
        ('location', '0023_remove_healthfacilitycontract_uq_hf_loc_contract_valid_and_more'),
        ('payment', '0010_unmatchedofflinepayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPaymentIdReservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('chf_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reserved_by_user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RS', 'Reserved'), ('US', 'Used'), ('CA', 'Cancelled')], default='RS', max_length=2)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
                ('reserved_hf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserved_payment_ids', to='location.healthfacility')),
                ('reserved_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserved_payment_ids', to='core.officer')),
                ('used_by_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_reservations', to='payment.payment')),
            ],
            options={
                'db_table': 'matchingPaymentIDReservation',
                'managed': True,
            },
        ),
    ]
