# Generated by Django 4.2.25 on 2025-11-27 08:53

import core.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_matchingpaymentidreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingpaymentidreservation',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='matchingpaymentidreservation',
            name='validity_from',
            field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='matchingpaymentidreservation',
            name='validity_to',
            field=core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True),
        ),
    ]
